inherit_from: .rubocop_todo.yml
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
AllCops:
  Exclude:
    - db/**/*
    - config/environments/*
    - bin/*
  NewCops: enable
